### ISSUE TITLE
ticket creation fails

### ISSUE THREAD

**Issue by behrisch** [mavam/trac-hub#14]
This is my first try with the script. I installed all dependencies and get this result:

```
bundle exec trac-hub 
/home/behrisch/trac-hub-master/vendor/bundle/ruby/2.4.0/gems/sequel-4.26.0/lib/sequel/database/schema_generator.rb:19: warning: constant ::Fixnum is deprecated
/home/behrisch/trac-hub-master/vendor/bundle/ruby/2.4.0/gems/sequel-4.26.0/lib/sequel/database/schema_generator.rb:19: warning: constant ::Bignum is deprecated
[2017-07-04 08:12:38] INFO  | loading tickets
[2017-07-04 08:12:38] INFO  | Last created issue on GitHub is '0'
[2017-07-04 08:12:38] INFO  | migrating issues
[2017-07-04 08:12:39] INFO  | creating issue 1 (testuser)
bundler: failed to load command: trac-hub (trac-hub)
NoMethodError: undefined method `[]' for nil:NilClass
  trac-hub:168:in `compose_issue'
  trac-hub:118:in `block in migrate_tickets'
  trac-hub:102:in `each'
  trac-hub:102:in `migrate_tickets'
  trac-hub:69:in `migrate'
  trac-hub:435:in `<top (required)>'
```

**Comment by behrisch** [comment]
I think, the problem may come from an empty ticket description.

**Comment by mavam** [comment]
Thanks for the report. Unfortunately I don't have the cycles right now to actively maintain the project.

I would be great if you could take the time to look at the backtrace and futz with the code, ideally leading to a quick fix. Especially an error like `NoMethodError: undefined method `[]' for nil:NilClass` is often quickly fixable by adding a branch, along the lines of `if x.nil? ...`.

**Comment by behrisch** [comment]
still finding my way around github and ruby but I tried to file a pull request #15
